### ISSUE TITLE
Add support for binlog_row_image=MINIMAL

### ISSUE THREAD

**Issue by sjmudd** [cashapp/spirit#221]
I just tried to run this on a test cluster and saw:

```
[user@host ~/spirit/cmd/spirit]$ ./spirit --host=127.0.0.1:3306 --username=whatever --password=whatever --database=whatever --table=whatever
INFO[0000] Starting spirit migration: concurrency=4 target-chunk-size=500ms table=whatever.whatever alter="engine=innodb"
spirit: error: binlog_row_image must be FULL
```

So I guess that spirit is reading binlog changes and thus requires the full binlog to work.
That design or requirement is completely fine but I think it would be wise to mention this in your [README.md](https://github.com/cashapp/spirit/blob/main/README.md) as it is not mentioned now and for users (like me) of a system with where `binlog_row_image=mininal` we would not currently be able to use this tool.

That requirement is fine. Perhaps `spirit` could enable full binlogging while doing the OSC and turn it again off afterwards?  I'm not suggesting you do that but it might be a way to handle such a configuration as I guess you only depend on this when running.  Again exact reasons of how or why you need this would be a useful mention.

**Comment by morgo** [comment]
Spirit doesn't technically require `binlog_row_image = FULL`, since it only extracts PKs from the binlog and always uses `REPLACE .. SELECT` from those keys. The reason this decision was made, was to simplify testing scope. We do not want to offer what we haven't tested.

I am going to break this issue into two parts:
1. Document that `binlog_row_image=FULL` is currently required.
2. Relax the requirement on `binlog_row_image=FULL`.

I will implement the first part shortly.

**Comment by sjmudd** [comment]
Hi Morgan.

Ok, that's good to hear. I hadn't taken time to look at the code to see why, but understand that if there's no hard requirement on usage of full binlogs then removing the unnecessary requirement would be good.

Both points you mention look good to me.

Thanks.

**Comment by morgo** [comment]
I took a look at part 2 as well, see https://github.com/cashapp/spirit/pull/235 It looks like there is some work besides just tests which will be required. (Yay tests. They broke where they were expected to.)

I'm going to keep this open for future implementers and change the status to help wanted.
