### ISSUE TITLE
When INSTANT is skipped it burns a row version on the shadow table 

### ISSUE THREAD

**Issue by reillski** [cashapp/spirit#241]
Hi,

This is more of a nit that will not affect majority of cases but raising for awareness. In MySQL 8 there is a limit on the max number of row versions you can have on a table.[1] For each instant ddl operation the `TOTAL_ROW_VERSIONS` value in `INFORMATION_SCHEMA.INNODB_TABLES` will increment. [2]

When `TOTAL_ROW_VERSIONS` is 64, `INSTANT` will not be possible on the next DDL. As expected, Spirit handles this `ERROR 4080` gracefully and creates a ghost table where the column is added. The nit here is that on the ghost table, Spirit executes the following which 'burns' a row version on the new table needlessly, since the shadow table is empty it should be possible to use non-instant DDL and 'save' a row version. 
```
CREATE TABLE _stock_old like stock;
ALTER TABLE ADD COLUMN ...; # uses instant by default
```

Changing this behavior may add needless complexity to optimize for the *very* small number of cases, (so feel free to close out :) ) but if a user is already hitting this 64 column limit on an existing table, it suggests this may be a frequent operation for them.

Thanks!
Marc

[1] https://dev.mysql.com/doc/refman/8.0/en/innodb-online-ddl-operations.html#:~:text=reset%20to%200.-,The%20maximum%20number%20of%20row%20versions%20permitted%20is%2064%2C%20as%20each,columns%20can%20be%20added%20or%20dropped%20instantly.%20Please%20use%20COPY/INPLACE.,-The%20following%20INFORMATION_SCHEMA 

[2] Note that these are tracked differently pre/post mysql 8.0.29. `INSTANT_COLS `vs `TOTAL_ROW_VERSIONS`
https://dev.mysql.com/doc/refman/8.0/en/information-schema-innodb-tables-table.html

**Comment by reillski** [comment]
Come to think of it, this is probably something that can be optimized in innodb. I will open a MySQL feature request to skip instant on an empty table.

**Comment by morgo** [comment]
Thank you for the feature request. This is something that we can consider in future. I believe there is an easy workaround is to change the `ALTER TABLE` on the empty table (_stock_new) to use the `COPY` algorithm. If that doesn't work, this will:

```
CREATE TABLE _stock_tmp LIKE stock;
ALTER TABLE _stock_tmp ADD COLUMN # uses instant
CREATE TABLE _stock_new LIKE _stock_tmp;
DROP TABLE _stock_tmp;
```

I am not surprised that Spirit handles the maximum number of instant operations reached correctly. By design it is agnostic as to what is instant/not-instant. The intention is that it can cater to future improvements where more operations may be instant _and_ that trying to determine if an operation will use instant is impossible. 

Having said that, we do have tests where we assert that certain known operations are instant or not. I think we should add some tests to assert that after 64 instants, it's not instant, and that the `TOTAL_ROW_VERSIONS` increases as expected. This will help us detect if MySQL semantics change too, since we test against multiple mysql versions.

**Comment by reillski** [comment]
FYI from latest releases, mysql feature req has been implemented:
> InnoDB: Executing ALTER TABLE with ADD COLUMN or DROP COLUMN against an empty table now uses the INPLACE algorithm by default instead of INSTANT. This change means the row version is no longer incremented for these simple operations. (Bug #113051, Bug #36004394)

[8.0.41 release notes](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-41.html)
