### ISSUE TITLE
defer-cutover flag issue on mysql 8.0.32

### ISSUE THREAD

**Issue by DevMasterSoonToBe** [cashapp/spirit#275]
Hi, 

I have an issue that defer-cutover flag don't work as expected on mysql 8.0.32. Basically it does the change on table right away, it doesn't seem to create sentinel table as it says in the Usage.md.

My command:
./spirit \
--host=${DB_HOST} \
--username=${DB_USERNAME} \
--password=${DB_PASSWORD} \
--database=xxxx \
--table=xxxxxxx \
--alter="xxxxxxx" \
--defer-cutover

output:
INFO[0000] Starting spirit migration: concurrency=4 target-chunk-size=500ms table=xxxxxx alter="xxxxxxxxx"
INFO[0000] apply complete: instant-ddl=true inplace-ddl=false

**Comment by DevMasterSoonToBe** [comment]
same happens if I put **_--defer-cutover=true_**

**Comment by morgo** [comment]
Hi @DevMasterSoonToBe , thanks for the question.

`defer-cutover` is not applying here because the operation was instant:
```
instant-ddl=true 
```

Spirit will always attempt `INSTANT` first (and some variants of `INPLACE`). If this is successful then the operation is complete, and it won't need to create a sentry table and apply the spirit algorithm. If you'd like to try an example to confirm defer cutover works, try creating an index.

We'll make this clearer in the docs in future.

**Comment by DevMasterSoonToBe** [comment]
Thanks, this explains it :)
