### ISSUE TITLE
Include package for asserting DB table properties

### ISSUE THREAD

**Issue by morgo** [cashapp/spirit#292]
## Context 

In our automation on top of Spirit, we use imperative schema changes. i.e. a user specifies an `ALTER` such as:

```
# v005__t1_add_new_col.sql
ALTER TABLE t1 ADD newcol INT;
```

Each of these changes is given a monotonic version (1, 2, 3..) and a `schema_version` table tracks which migrations have been applied. The readiness check for the service ensures that the installed DB migrations matches what the service knows about. We then have the following behaviours:

1. If the installed DB version is greater than what the code knows about: **No issue.**
2. If the installed DB version is less than what the code knows about: **Fail readiness check**.

I would like to slowly switch to using declarative changes (with [Skeema](https://github.com/skeema/skeema)), but this has two challenges:

1. Declarative changes no longer have a version. We've tried to think of ways to work around this. It's not easy and trying to shoe-horn on one, loses a lot of the advantages of declarative too.
2. By not having a version, we are thus losing the readiness check. This has helped catch historical issues, and we don't want to just give it up.

What I am instead proposing, is we offer an _alternative readiness check_ which is not based on version but instead checks for the existence of table properties.

## Asserting for Table Properties

You could argue this is not a spirit feature, but because spirit already has an infoschema package (table) extending it to support this is not difficult.

What I would like to propose is a package called `asserty`.  The readiness check can use it as follows:

```
..
/*
CREATE TABLE asserty_test (
id int unsigned NOT NULL AUTO_INCREMENT,
name varchar(115),
age int NOT NULL,
PRIMARY KEY (id, age),
INDEX idx_name (name),
INDEX idx_age (age)
*/

tbl, err := LoadTable(db, "test", "asserty_test")
if err != nil {
 return err
}
if !(tbl.ContainsColumns("name", "age") && tbl.ContainsIndexes("idx_name", "idx_age")) {
// not good, service is not ready
}
// all good

```

In this example it's returning a `bool` and not just failing like an assertion would. The exact design should be discussed here, but our use-case is in the readiness check rather than in test code.

**Comment by evanelias** [comment]
Just saw your DM – sorry for the delay, I don't often check Slack lately. Your approach in #293 looks great. Just wanted to add some random thoughts re: Skeema interactions with schema versioning / service readiness checks / app deploy gating in general, since it's a topic I've noodled over a lot but haven't written down anywhere yet 😄 

Direct support for declarative checks in Skeema might be nice in the future (as a separate subcommand perhaps) but there's a lot of complexity due to varying requirements between companies. For example some might need the ability to express some more nuanced edge-cases, e.g. gating a readiness check on a column type change from int to bigint, or a default value change, etc. Also complexity around declarative checks for sharded environments, instead of just a singular DB.

One simpler approach that might appear sooner in Skeema is a subcommand to dump any introspected schema as JSON output. That way, companies could write arbitrary automation (including readiness checks) more easily, without having to duplicate any of Skeema's introspection logic. Longer-term this might get wrapped into a separate daemon which can cache the metadata (potentially across multiple db servers/shards) to avoid having to re-run expensive information_schema queries.

That said, there's also a pre-existing alternative non-declarative solution which has worked well for some users, which I think of as a Release Engineering or GitOps type approach. This involves having custom automation (wrapping `skeema push`) which is responsible for tracking schema change completion. A few variations that can work well:

a) Incremental git tag versioning: prior to running `skeema push`, the automation creates a git tag using an incremental version number. After the push completes, the automation logs it to a DB. Service readiness checks can query that DB to see if the version number they need has been applied already.

b) Pull request numbering: similar to (a), but instead of using git tags and incremental numbers, automation is driven by GitHub Actions and uses pull request numbers. This works well because it's easy for engineers to cross-reference, especially for monorepos that combine the service code and schema definitions in the same repo. The downside is that PRs might be applied out-of-order, so readiness checks need to express the specific PR number(s) that they depend on, rather than doing a >= comparison.

c) Descriptive tagging: similar to (a), but instead of incremental numbers, engineers explicitly pick descriptive tag names for commits. Automation checks for tags on the new commits when making a schema change, and logs this to the DB on completion, as in (a). Service readiness checks can query the DB for the specific named tags that they depend on. The advantage here is something like "add-age-col-and-index" is immediately clearer than "v1234".

These all have potential pros and cons relative to the pure declarative approach. So far in terms of developer experience I've seen a variety of opinions and preferences, so I'd love to get a better sense of what resonates and what doesn't over time!

**Comment by morgo** [comment]
Thanks for the feedback. I do like (a), we may have to investigate it!
