### ISSUE TITLE
Extend `--skip-drop-after-cutover` option 

### ISSUE THREAD

**Issue by samongyr-sq** [cashapp/spirit#296]
Spirit has a `--skip-drop-after-cutover` option to retain the pre-alter table after an OSC completes. When enabled, Spirit will rename the old table to `<db>._<table>_old` (e.g. `mydb.table` -> `mydb._table_old`) instead of dropping it. 

The problem with this is that if `mydb._table_old` is _not_ cleaned up, it appears that subsequent migrations on `mydb.table` will cause the previously retained table to be silently dropped by Spirit when it kicks off the new migration. 

It would be nice to extend the `--skip-drop-after-cutover` option so users can (1) specify a different database for old tables to be renamed to and/or (2) add an additional suffix to the old table name (e.g. `_table_old_<ts>`) to avoid name collisions.

**Comment by morgo** [comment]
We discussed this internally. The option `--skip-drop-after-cutover` was designed for MySQL 5.7, where drop could cause a stall. We have a limited use-case for it now (but still no plans to remove it).

I propose that instead of adding a new option, we redefine the behavior to match your requirements: rename to `_table_old_<ts>`. This will fail to drop on new launches of the tool, but I think that's fine. We have no explicit v1 compatibility guarantee and can do this.

**Comment by jayjanssen** [comment]
taking a look at this

**Comment by jayjanssen** [comment]
@pamelayin Take a look at my PR as mentioned
