### ISSUE TITLE
Spirit fails on metadata lock when table name is really long

### ISSUE THREAD

**Issue by pamelayin** [cashapp/spirit#347]
Square has some apps with long table names. It fails to start due to lock name over the length limit specified [here](https://github.com/cashapp/spirit/blob/fd5b3496bb6a8f0329f96f52b855d23a5fa0d435/pkg/dbconn/metadatalock.go#L30-L32).

**Comment by morgo** [comment]
Thanks for the bug report. I'll look into if this can be fixed.

64 chars is the limit for metadata locks, but what we can do is try and take a shorter lock name.

**Comment by morgo** [comment]
I looked at this. This is a regression of https://github.com/cashapp/spirit/pull/342

The maximum tablename supported by default is `54` characters (versus in MySQL: 64). This is because we need to support a table of the name:

```
_%s_sentinel
```

However, when the option `SkipDropAfterCutover` is enabled, the tableName must be 43 characters or less. These are well tested in https://github.com/cashapp/spirit/blob/main/pkg/check/tablename.go .

The regression is because the MDL lock is using the full quoted name of the table and the schema (which our schema names tend to be large too, so it could eat into the maximum size quickly). We'll have to change it back to just being the table name. I will ask @prudhvi to work on it, since it affects some of his other code.

**Comment by pamelayin** [comment]
We implemented similar lock feature to shift in general and ran into a table name that was 47 characters long. On shift, we created lock name shift_schema_tablename which became 81 characters long altogether. On our end, we're thinking of hashing the table name as potential solution.

**Comment by morgo** [comment]
Our fix here is just to use table name and not schema. Thus, you will no longer be able to run concurrent modifications across schemas with tables of the same name. I think this is an acceptable limitation for now.

We can not reduce the 54/43 char limit much further, since these are unhashed table objects. We could document it better though.
