### ISSUE TITLE
error flushing binary log: context canceled

### ISSUE THREAD

**Issue by DevMasterSoonToBe** [cashapp/spirit#362]
Hi, 

We are trying to resume spirit after reducing binlog_retention_period on mysql engine aws rds from 168 hours to 3 hours and we get this error:

INFO[1114] migration status: state=copyRows copy-progress=1008972824/10242655371 9.85% binlog-deltas=0 total-time=18m34s copier-time=18m30s copier-remaining-time=195h11m2s (-90h10m from 18m ago) copier-is-throttled=false conns-in-use=4
INFO[1123] high chunk processing time. time: 7.172933698s threshold: 2.5s target-rows: 6013 target-ms: 500ms new-target-rows: 601
INFO[1128] high chunk processing time. time: 2.903141676s threshold: 2.5s target-rows: 182 target-ms: 500ms new-target-rows: 18
INFO[1134] high chunk processing time. time: 2.586003633s threshold: 2.5s target-rows: 366 target-ms: 500ms new-target-rows: 36
INFO[1134] closing canal
INFO[1134] syncer is closing...
WARN[1134] releasing metadata lock for xxx.xxxx
ERRO[1134] error flushing binary log: context canceled
INFO[1134] finished periodic flush of binary log: total-duration=6m48.802875614s batch-size=1000
INFO[1134] kill last connection id 1746825
INFO[1134] syncer is closed
spirit: error: Error 1205 (HY000): Lock wait timeout exceeded; try restarting transaction

This is spirit command we used:
./spirit --host=${DB_HOST} 
--username=${DB_USERNAME} 
--password=${DB_PASSWORD} 
--database=xxxx 
--table=xxxxx 
--alter="PARTITION BY KEY() PARTITIONS 8" 
--defer-cutover=true 
--checksum=false 
--skip-drop-after-cutover=true 
--threads=32

As stated at the top issue started when we reduced binlog_retention_period on rds instance(when it was 168 it was running fine without any issues). Could you advise what is the issue here? Configuration/binlog retention needs to be set to specific time etc?

**Comment by morgo** [comment]
Spirit is abandoning this migration because it has encountered a deadlock.

Your configuration seems off: 32-threads is very high, and it is probably contributing to the high chunk processing teams, and I assume your MySQL server is completely overloaded. Each of those threads is copying maybe 18/36/601 rows at a time, which is not many.

If you need to apply the schema change faster, you are going to be much better off picking a much smaller thread count (i.e. 4-8 or much around the number of vCPUs on your RDS instance), but set the target-chunk-time to 5s.

This is more likely to run smoother, and hopefully prevent the long overloading which probably contributes to your deadlocks.

**Comment by DevMasterSoonToBe** [comment]
Thanks, we made adjustments
